language: php

php:
  - 5.3

env:
  - SYMFONY_VERSION=v2.0.7
#  - SYMFONY_VERSION=origin/2.0
#  - SYMFONY_VERSION=origin/master

before_script: 
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update

script: phpunit

notifications:
  email:
    - richard.tribes@gmail.com
