
<div id="<?php echo $pager->getSuffixName(); ?>" style="text-decoration:underline;">
<?php
    if ($pager->getTotalPage() > 1) {
        $counter = 0;
        foreach ($pager->buildPager() as $pagerKey=>$pagerItem) {
            $counter++;
            if ($pager->isCurrentPage($pagerItem->label)) {
                echo '<strong>' . $pagerItem->label . '</strong>';
            } else if (isset($pagerItem->uri)) {
                echo '<a href="' . $pagerItem->uri . '" title="' . $pagerItem->title . '">'
                    . $pagerItem->label . '</a>';
            } else {
                echo $pagerItem->label;
            }
            if ($counter < $pager->getTotalPage()) echo '|' ;
        }
    }
?>
</div>